disabled_rules:
    - empty_enum_arguments
    - line_length

excluded:
    - Pods
    - Carthage
    - Fastlane
    - build
    - DerivedData
    - Yummie/SwiftGen/Assets.generated.swift

# List of rules to apply:
opt_in_rules:
    # Basic rules:
    - trailing_whitespace
    - line_length
    - vertical_whitespace
    - force_cast
    - force_try
    - force_unwrapping
    - unused_optional_binding
    
    # Style rules:
    - closure_spacing
    - colon
    - comma
    - control_statement
    - discouraged_direct_init
    - empty_count
    - empty_parameters
    - first_where
    - function_body_length
    - identifier_name
    - implicit_return
    - large_tuple
    - leading_whitespace
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - no_extension_access_modifier
    - number_separator
    - object_literal
    - operator_usage_whitespace
    - redundant_discardable_let
    - redundant_nil_coalescing
    - redundant_optional_initialization
    - redundant_set_access_control
    - redundant_type_annotation
    - redundant_void_return
    - return_arrow_whitespace
    - sorted_first_last
    - statement_position
    - switch_case_alignment
    - trailing_closure
    - trailing_semicolon
    - unused_closure_parameter
    - unused_setter_value
    - weak_delegate
#  - conditional_returns_on_newline
#  - unused_import
#  - overridden_super_call
#  - private_outlet
#  - no_grouping_extension
#  - missing_docs
#  - empty_enum_arguments

#
# # Linting configuration:
# line_length:
#   warning: 120
#   error: 200
#
