fastlane_version '2.213.0'
default_platform :ios

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :unit_test do
        run_tests(
          scheme: "Yummie",
          device: "iPhone 11",
          cloned_source_packages_path: "SourcePackages"
        )
      end
end


